# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AB Inbev Scholarships
email: ariel.hidal@anheuser-busch.com
description: > # this means to ignore newlines until "baseurl:"
  Information about AB Inbev's scholarship for Low Income High Potential students

baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "http://webjeda.com" # the base hostname & protocol for your site

#sidebar
default-image: abilogo.png  # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Test
copyright:
   name: Test
   link:

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

#social

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/abinbev
fb-page-title: AB Inbev

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

